name: CI

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  version: 10.x
                  registry-url: https://registry.npmjs.org/
            - name: Build
              run: |
                  npm install
                  npm run build --if-present
            - name: dist
              run: npm publish
              env:
               NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
