name: pay.fun_CICD
on:
  push:
      branches: [ main ]
      # pull or push to on CICD
      pull_request:
        branches: [ main ]
#      paths-ignore: # 下列文件的变更不触发部署
#          - README.md
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@mrin # 检出副本 测试代码为mrin
      - name: Use Node.js  # 使用官方node
        uses: actions/setup-node@v1
  npm_issue :
    name: build
    needs: checkout
    steps:
      - name: npmi # npm i 安装依赖
          run: npm install
      - name: Build              # 第三步，打包代码
          run: npm run build --if-present
