name: pay.fun_CICD
on:
  push:
      branches: [ main ]
      # pull or push to on CICD
#      paths-ignore: # 下列文件的变更不触发部署
#          - README.md
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main # 检出副本 测试代码为mrin
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
  npm_issue :
    name: build
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install And Build            
        run: npm install && npm run build 
        
